"""Generate app dictionaries and server report labels from one reviewed UTF-8 catalog."""
from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
codes=['mk','de','it','es','fr','sr','pt-BR','el']
catalog={code:{} for code in codes}
for index,line in enumerate((root/'translations/catalog.tsv').read_text().splitlines(),1):
    if not line.strip(): continue
    row=line.split('\t')
    if len(row)!=9 or any(not x.strip() for x in row): raise ValueError(f'Incomplete row {index}')
    for code,value in zip(codes,row[1:]):
        if row[0] in catalog[code]: raise ValueError(f'Duplicate key {row[0]}')
        catalog[code][row[0]]=value
folder=root/'app/src/main/java/com/paytimeshift/pts/ui/translations';folder.mkdir(parents=True,exist_ok=True)
def quoted(value): return json.dumps(value,ensure_ascii=False).replace('$','\\$')
for code,values in catalog.items():
    name=code.replace('-','')
    text='// Generated by tools/generate_translations.py from translations/catalog.tsv.\npackage com.paytimeshift.pts.ui.translations\n\ninternal val catalog'+name+' = mapOf(\n'
    text+=',\n'.join('    '+quoted(key)+' to '+quoted(value) for key,value in values.items())+'\n)\n'
    (folder/f'Catalog{name}.kt').write_text(text)
(root/'backend/translations.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
print(f'{len(catalog["de"])} translated messages × {len(codes)} languages generated')
